apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  catalog-service
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: catalog-service:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        ports:
          - containerPort: 9001
        env:
        - name: BPL_JVM_THREAD_COUNT
          value: "50"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://polar-postgres/polardb_catalog
        - name: SPRING_PROFILES_ACTIVE
          value: testdata

